//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSitem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TBLMUSTERI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMUSTERI()
        {
            this.TBLSATISLAR = new HashSet<TBLSATISLAR>();
        }
    
        public int MUSTERI_ID { get; set; }
        [Required(ErrorMessage ="Bu Alanı Boş Bırakamazsınız !!")]
        [StringLength(50,ErrorMessage ="MAx karakter sayısı aşıldı..")]
        public string MUSTERİ_AD { get; set; }
        [Required(ErrorMessage = "Bu Alanı Boş Bırakamazsınız !!")]
        [StringLength(50, ErrorMessage = "MAx karakter sayısı aşıldı..")]
        public string MUSTERI_SOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATISLAR> TBLSATISLAR { get; set; }
    }
}
